image: bitwalker/alpine-elixir-phoenix

services:
  - postgres:latest

variables:
  POSTGRES_DB: "student_manager_test"
  POSTGRES_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "postgres"
  MIX_ENV: "test"

before_script:
  - apt-get update && apt-get -y install postgresql-client chromium chromedriver
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - cd assets && npm install && cd -
  - mix ecto.create
  - mix ecto.migrate

 
mix:
  script:
    - mix test
